import type { Metadata } from "next";
import { Montserrat, Rubik } from "next/font/google";
import "@/app/globals.css";
import "@/styles/containers.css";
import "@/styles/text.css";
import "@/styles/gradients.css"
import { Toaster } from "@/components/ui/sonner";
import { NextAuthProvider } from "@/components/auth-provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Saas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={`${montserrat.variable} antialiased`}>
        <NextAuthProvider>
          <div className={`${rubik.variable}`}>
            {children}
            <Toaster />
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
